get_filename_component(_vnm_plot_workspace_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
get_filename_component(_vnm_plot_shared_fetch_root "${CMAKE_CURRENT_LIST_DIR}/../../../varinomics/fetched_libs" ABSOLUTE)

set(_vnm_plot_glm_source_dir "${_vnm_plot_shared_fetch_root}/glm-src")
if(EXISTS "${_vnm_plot_glm_source_dir}/CMakeLists.txt")
    set(FETCHCONTENT_SOURCE_DIR_GLM "${_vnm_plot_glm_source_dir}" CACHE PATH "" FORCE)
    set(FETCHCONTENT_SOURCE_DIR_glm "${_vnm_plot_glm_source_dir}" CACHE PATH "" FORCE)
else()
    set(_vnm_plot_glm_source_dir "${_vnm_plot_workspace_root}/glm-src")
    if(EXISTS "${_vnm_plot_glm_source_dir}/CMakeLists.txt")
        set(FETCHCONTENT_SOURCE_DIR_GLM "${_vnm_plot_glm_source_dir}" CACHE PATH "" FORCE)
        set(FETCHCONTENT_SOURCE_DIR_glm "${_vnm_plot_glm_source_dir}" CACHE PATH "" FORCE)
    endif()
endif()

set(_vnm_plot_freetype_source_dir "${_vnm_plot_shared_fetch_root}/freetype-src")
if(EXISTS "${_vnm_plot_freetype_source_dir}/CMakeLists.txt")
    set(FETCHCONTENT_SOURCE_DIR_FREETYPE "${_vnm_plot_freetype_source_dir}" CACHE PATH "" FORCE)
    set(FETCHCONTENT_SOURCE_DIR_freetype "${_vnm_plot_freetype_source_dir}" CACHE PATH "" FORCE)
else()
    set(_vnm_plot_freetype_source_dir "${_vnm_plot_workspace_root}/freetype-src")
    if(EXISTS "${_vnm_plot_freetype_source_dir}/CMakeLists.txt")
        set(FETCHCONTENT_SOURCE_DIR_FREETYPE "${_vnm_plot_freetype_source_dir}" CACHE PATH "" FORCE)
        set(FETCHCONTENT_SOURCE_DIR_freetype "${_vnm_plot_freetype_source_dir}" CACHE PATH "" FORCE)
    endif()
endif()

set(_vnm_plot_msdfgen_source_dir "${_vnm_plot_shared_fetch_root}/msdfgen-src")
if(EXISTS "${_vnm_plot_msdfgen_source_dir}/CMakeLists.txt")
    set(FETCHCONTENT_SOURCE_DIR_MSDFGEN "${_vnm_plot_msdfgen_source_dir}" CACHE PATH "" FORCE)
    set(FETCHCONTENT_SOURCE_DIR_msdfgen "${_vnm_plot_msdfgen_source_dir}" CACHE PATH "" FORCE)
else()
    set(_vnm_plot_msdfgen_source_dir "${_vnm_plot_workspace_root}/msdfgen-src")
    if(EXISTS "${_vnm_plot_msdfgen_source_dir}/CMakeLists.txt")
        set(FETCHCONTENT_SOURCE_DIR_MSDFGEN "${_vnm_plot_msdfgen_source_dir}" CACHE PATH "" FORCE)
        set(FETCHCONTENT_SOURCE_DIR_msdfgen "${_vnm_plot_msdfgen_source_dir}" CACHE PATH "" FORCE)
    endif()
endif()

unset(_vnm_plot_glm_source_dir)
unset(_vnm_plot_freetype_source_dir)
unset(_vnm_plot_msdfgen_source_dir)
unset(_vnm_plot_shared_fetch_root)
unset(_vnm_plot_workspace_root)
